# -*- coding: utf-8 -*-
# Short Japanese glosses for vocab terms, keyed by exact term text (as produced
# by extract_from_docx.py). Matched case-sensitively first, then case-insensitively
# as a fallback (see merge_glosses.py).

GLOSSES = {
"sent away": "送り出された",
"air-raids": "空襲",
"in the heart of the country": "田舎の奥深くに",
"railway station": "鉄道の駅",
"servants": "使用人たち",
"come into": "（物語などに）登場する",
"shaggy": "ぼさぼさの",
"once": "かつて／すぐに",
"odd-looking": "奇妙な見た目の",
"keep on": "〜し続ける",
"pretending": "ふりをすること",
"blowing his nose": "鼻をかむこと",
"hide": "隠す",
"gone upstairs": "二階へ上がった",
"all talked it over": "みんなでよく話し合った",
"chap": "やつ、男",
"dear": "（名詞）いい人、優しい人",
"bad-tempered": "機嫌が悪い",
"Don't go on talking like that": "そんな話し方を続けないで",
"Trying to talk like Mother": "お母さんの真似をして話そうとして",
"better": "〜したほうがよい（had better）",
"There's sure to be a row": "きっと騒ぎになる",
"passages": "廊下",
"suddenly": "突然",
"empty": "空っぽの",
"creepy": "気味が悪い",
"owl": "フクロウ",
"shall": "〜するつもりだ（意志のshall）",
"explore": "探検する",
"along": "一緒に／〜に沿って",
"eagles": "ワシ",
"stags": "雄鹿",
"hawks": "タカ",
"Badgers": "アナグマ",
"Foxes": "キツネ",
"Rabbits": "ウサギ",
"steady": "絶え間ない",
"thick": "濃い、激しい",
"neither": "どちらも〜ない",
"nor": "〜もまた〜ない",
"stream": "小川",
"set apart": "特別に取っておく",
"grumbling": "不平を言うこと",
"meantime": "その間",
"pretty well off": "かなり恵まれている",
"wireless": "ラジオ",
"sort of house": "そういう種類の家",
"unexpected": "予想外の",
"armour": "甲冑（かっちゅう）",
"hung with": "（壁などが）〜で覆われた",
"led out": "通じていた",
"whole series": "一連の",
"Bible": "聖書",
"church": "教会",
"shortly": "まもなく",
"looked into": "のぞき込んだ",
"empty except": "〜以外は空っぽの",
"looking-glass": "鏡",
"trooped": "ぞろぞろと歩いた",
"behind": "〜を除いて／後ろに",
"worthwhile": "する価値がある",
"mothballs": "防虫剤",
"feel": "感触",
"immediately": "すぐに",
"rubbed": "こすりつけた",
"against": "〜に押し当てて",
"foolish": "愚かな",
"shut": "閉じ込める",
"oneself": "自分自身",
"further": "さらに奥へ",
"stretched": "伸ばした",
"bump": "ぶつける",
"woodwork": "木材、木の部分",
"tips": "先端",
"enormous": "巨大な",
"folds": "ひだ、重なった部分",
"crunching": "ザクザクという音を立てること",
"instead": "その代わりに",
"powdery": "粉のような",
"extremely": "非常に",
"queer": "奇妙な",
"rubbing": "こすれること",
"prickly": "チクチクする",
"branches": "枝",
"exclaimed": "叫んだ",
"inches": "インチ",
"ought": "〜すべきだ（ought to）",
"frightened": "おびえた",
"inquisitive": "詮索好きな",
"trunks": "（木の）幹",
"doorway": "戸口",
"glimpse": "ちらっと見えること",
"silly": "ばかげた",
"daylight": "日中の明かり",
"towards": "〜の方へ",
"lamp-post": "街灯柱",
"pitter": "ぱたぱた（足音の擬音の一部）",
"patter": "ぱたぱたという音",
"carried over his head": "頭上にかざしていた",
"waist upwards": "腰から上",
"shaped": "形をしていた",
"glossy": "つやのある",
"hoofs": "ひづめ",
"caught up": "まくり上げられていた",
"trailing": "引きずること",
"woollen": "毛織の",
"rather": "いくぶん、かなり",
"reddish": "赤みを帯びた",
"pleasant": "感じのよい",
"pointed": "とがった",
"beard": "あごひげ",
"curly": "縮れた",
"stuck": "突き出ていた（stickの過去形）",
"forehead": "額（ひたい）",
"parcels": "小包",
"What with": "〜やら〜やらで",
"looked": "〜のように見えた",
"gave": "与えた（giveの過去形）",
"start": "はっと驚くこと",
"gracious": "まあ、なんてこと（驚きの表現）",
"busy picking up": "拾い集めるのに大忙しで",
"reply": "返事をする",
"bow": "お辞儀",
"Daughter of Eve": "イブの娘（人間の女の子）",
"quite": "まったく、かなり",
"forgive me": "失礼ですが、許してください",
"what they call": "いわゆる〜、〜と呼ばれるもの",
"in fact": "つまり、実は",
"puzzled": "困惑した",
"stupid": "愚かな",
"Son of Adam": "アダムの息子（人間の男の子）",
"That is to say": "つまり",
"in time": "間に合って、早い段階で",
"went on": "続けた",
"land": "国、地方",
"lies": "位置している、広がっている（lieの三単現）",
"Wild Woods": "野生の森",
"through": "〜を通って",
"melancholy": "物悲しい",
"If only": "〜さえすれば",
"no doubt": "間違いなく",
"at all": "まったく（〜ない）",
"almost laughing": "笑いそうになりながら",
"at least": "少なくとも",
"Meanwhile": "一方、その間",
"catch cold": "風邪をひく",
"eternal": "永遠の",
"reigns": "支配する（三単現）",
"how would it be if": "〜したらどうだろう",
"whether": "〜かどうか",
"roaring": "轟々と燃える",
"sardines": "イワシ",
"hold the umbrella over": "〜に傘をさしかける",
"off we go": "さあ、行こう",
"arm in arm": "腕を組んで",
"creature": "生き物",
"all their lives": "生まれてからずっと",
"ground": "地面",
"rough": "でこぼこした",
"little hills up and little hills down": "小さな丘が上ったり下ったり",
"valley": "谷",
"straight": "まっすぐに",
"unusually": "異常に",
"cave": "洞窟",
"found herself": "気づくと〜していた",
"blinking": "まばたきすること",
"stooped": "身をかがめた",
"flaming": "燃えている",
"neat": "こぎれいな",
"tongs": "火ばさみ",
"lit": "火をつけた（lightの過去形）",
"shan't be long": "すぐに済むだろう",
"put": "置いた（put ... onで「かける・のせる」）",
"nicer": "もっと素敵な",
"carpet": "じゅうたん",
"dresser": "食器棚",
"mantelpiece": "暖炉の上の飾り棚",
"over the fire": "暖炉の上に",
"corner": "隅",
"lead to": "〜に通じる",
"shelf": "棚",
"full of": "〜でいっぱいの",
"setting out": "並べること",
"Letters": "書簡集",
"Ways": "習性",
"Monks": "修道士",
"Gamekeepers": "猟場番人",
"Study": "研究",
"Popular Legend": "民間伝説",
"Myth": "神話",
"Now": "さあ（呼びかけ）",
"wonderful": "素晴らしい",
"lightly": "軽く",
"boiled": "ゆでた",
"sugar-topped": "砂糖をまぶした",
"tired of": "〜に飽きる",
"tales": "物語",
"midnight": "真夜中",
"wells": "泉",
"Dryads": "ドライアド（木の精）",
"came out": "出てきた",
"hunting": "狩り",
"parties": "一行、隊",
"after": "〜を追って",
"milk-white": "乳白色の",
"stag": "雄鹿",
"wishes": "願い事",
"feasting": "宴を開くこと",
"treasure-seeking": "宝探し",
"wild": "野生の",
"Red Dwarfs": "赤い小人",
"mines": "鉱山",
"beneath": "〜の下に",
"green": "緑の",
"fat": "太った",
"donkey": "ロバ",
"Bacchus": "バッカス（酒の神）",
"run": "流れる",
"whole": "森全体（wholeの形容詞用法）",
"give itself up to": "〜にふける、〜に身を委ねる",
"jollification": "お祭り騒ぎ",
"on end": "何週間も続けて",
"added": "付け加えた",
"gloomily": "陰気に",
"cheer himself up": "元気を出すために",
"took out": "取り出した",
"flute": "笛",
"straw": "わら",
"tune": "曲",
"all at the same time": "同時に全部",
"shook": "我に返った（shake oneselfの過去形）",
"herself": "彼女自身",
"stop you": "あなたを止める",
"do love": "本当に大好きだ（強調のdo）",
"only": "〜だけ",
"meant to": "〜するつもりだった",
"It's no good now": "もう手遅れだ",
"laying down": "下に置くこと（lay down）",
"shaking": "振ること",
"sorrowfully": "悲しそうに",
"jumping up": "飛び上がること",
"at once": "すぐに",
"wondering": "不思議に思うこと",
"moment": "瞬間",
"later": "後で",
"Whatever is the matter": "一体どうしたの",
"for": "なぜなら（接続詞、becauseの意味）",
"filled with tears": "涙でいっぱいになった",
"tears": "涙",
"trickling down": "したたり落ちる",
"cheeks": "頬",
"running off": "流れ落ちる",
"at last": "ついに",
"howl": "大声で泣く",
"in great distress": "ひどく取り乱して",
"continued": "続けた",
"sobbing": "すすり泣くこと",
"even when": "〜のときでさえ",
"went over": "近づいた",
"put her arms round": "腕を回した",
"merely": "ただ〜だけ",
"wringing": "絞ること",
"whenever": "〜するたびに",
"presently": "まもなく",
"damp": "湿った",
"patch": "一部分",
"bawled": "大声で叫んだ",
"in his ear": "彼の耳もとで",
"be ashamed of yourself": "恥を知りなさい",
"on earth": "一体全体（強調表現）",
"such a": "こんなにも",
"nicest": "一番素敵な",
"I don't suppose": "〜ではないと思う",
"beginning of the world": "世界の始まり",
"Taken service under": "〜に仕えている",
"in the pay of": "〜に雇われて",
"Why": "あら、まあ（間投詞）",
"under her thumb": "完全に支配して",
"think of that": "それを考えてみて",
"awful": "ひどい",
"pay you for": "あなたへの報酬",
"the worst of it": "それの最悪な点",
"groan": "うめき",
"kidnapper": "誘拐犯",
"poor innocent": "かわいそうな無邪気な",
"done me any harm": "私に何の害も与えていない",
"pretend to be": "〜のふりをする",
"friendly with": "〜と親しく",
"invite": "招待する",
"all for the sake of": "すべて〜のために",
"lulling": "眠らせること",
"asleep": "眠って",
"handing it over to": "それを〜に引き渡すこと",
"sort": "種類",
"truthful": "正直な",
"too hard on him": "彼に厳しすぎる",
"pretty": "かなり（副詞）",
"re so sorry for": "とても気の毒に思う（be so sorry for）",
"I'm sure": "きっと〜だ",
"this very moment": "まさに今この瞬間",
"turning": "（顔色などが）変わること",
"white": "青ざめた",
"had orders from": "〜から命令を受けていた",
"if ever": "もし〜ならば",
"was to": "〜することになっていた（be to構文）",
"meaning to": "〜するつもりで",
"wait till": "〜まで待つ",
"Indeed": "本当に",
"find out": "見つけ出す",
"cut off": "切り落とす",
"sawn off": "のこぎりで切り落とされる",
"plucked out": "引き抜かれる",
"wave her wand over": "〜の上で杖を振る",
"cloven hoofs": "割れたひづめ",
"turn them into horrid": "それらをひどいものに変える",
"solid hoofs": "一体型のひづめ",
"wretched": "みじめな",
"extra": "特別に",
"specially": "とりわけ",
"shall be only": "〜になるだけだろう",
"statue": "像",
"horrible": "恐ろしい",
"thrones": "王座",
"are filled": "満たされる",
"goodness": "おや、まあ（驚きの表現）",
"knows": "知っている（knowの三単現）",
"I see that now": "今それがわかった",
"give you up to the Witch": "あなたを魔女に引き渡す",
"now that": "今や〜なので",
"be off": "出発する",
"suppose": "〜だと思う",
"find your own way": "自分で道を見つける",
"spies": "スパイ",
"on her side": "彼女の味方をして",
"got up": "立ち上がった",
"left": "置いていった（leaveの過去形）",
"put up": "（傘を）さした",
"journey back": "帰り道",
"not at all": "全く〜ない",
"stole along": "こっそり進んだ",
"without speaking a word": "一言も話さずに",
"kept to": "〜に沿って進んだ",
"relieved": "ほっとした",
"reached": "たどり着いた",
"know your way": "道がわかる",
"could just see": "かろうじて見えた",
"be off home": "家に帰る",
"ever": "果たして、これまでに",
"forgive": "許す",
"by the hand": "手を取って",
"do hope": "心から願う（強調のdo）",
"get into": "（面倒などに）巻き込まれる",
"dreadful": "ひどい",
"trouble": "面倒、困難",
"on my account": "私のせいで",
"Farewell": "さようなら",
"Perhaps": "もしかしたら",
"as quickly as her legs would carry her": "足の許す限り速く",
"brushing past": "かすめて通ること",
"jumping out of": "〜から飛び出すこと",
"tightly": "しっかりと",
"panting for breath": "息を切らして",
"shouted": "叫んだ",
"all right": "大丈夫",
"ran out of": "〜から駆け出した",
"repeated": "繰り返した",
"What on earth": "一体全体何を",
"in amazement": "驚いて",
"hiding": "隠れること",
"Poor old": "かわいそうな",
"noticed": "気づいた",
"'ve been away": "ずっと出かけていた（have been awayの一部）",
"for hours and hours": "何時間も",
"stared at": "じっと見つめた",
"Batty": "頭がおかしい",
"tapping his head": "頭をとんとん叩くこと",
"just after": "〜のすぐ後",
"all sorts of": "あらゆる種類の",
"Don't be silly": "ばかなことを言わないで",
"come out of": "〜から出てくる",
"a moment ago": "ついさっき",
"making up a story": "話をでっち上げること",
"for fun": "面白半分に",
"why shouldn't she": "彼女がそうしてはいけない理由はない",
"come and see": "来て見て",
"did not know what to think": "どう考えればいいかわからなかった",
"excited": "興奮した",
"rushed ahead of": "〜より先に駆け出した",
"flung": "勢いよく開けた（flingの過去形）",
"open": "開いた",
"for yourselves": "自分自身の目で",
"goose": "まぬけさん",
"pulling": "引っ張ること",
"apart": "ばらばらに",
"ordinary": "普通の",
"the back of": "〜の奥、裏側",
"looked in": "中をのぞき込んだ",
"perfectly": "全くの",
"hooks": "フック",
"rapped": "こつこつと叩いた",
"knuckles": "指の関節",
"solid": "頑丈な、本物の",
"hoax": "作り話、いたずら",
"taken us in": "私たちをだました（take inの現在完了）",
"admit": "認める",
"going a bit far": "ちょっとやりすぎだ",
"had": "した（haveの過去形）",
"joke": "冗談",
"Hadn't you better": "〜したほうがいいのでは",
"drop": "やめる",
"burst into tears": "泣き出した",
"made it up with": "〜と仲直りできた",
"at any moment": "いつでも",
"could have": "〜できただろうに（仮定法）",
"brought herself to": "〜する気になれた",
"bring herself to say": "言う気になる",
"spiteful": "意地悪な",
"occasion": "場合、機会",
"ought to have been delightful": "楽しいはずだった（仮定法過去完了）",
"scattered": "散らばった",
"business": "出来事、事柄",
"there was nothing for it but to": "〜するしかなかった",
"feeling about for": "手探りで捜すこと",
"Thank goodness": "ありがたい",
"of its own accord": "ひとりでに",
"robin": "コマドリ",
"Make it Pax": "仲直りにしよう",
"on fire": "燃えているように",
"served him": "彼の役に立った",
"pulled": "引いた",
"recovered themselves": "落ち着きを取り戻した",
"pray": "一体全体（古風な間投詞）",
"address": "話しかけ方",
"overgrown": "伸び放題の",
"dwarf": "小人",
"your Majesty": "陛下",
"too confused": "あまりに混乱して",
"idiot": "ばか者",
"whatever else": "他に何であろうと",
"may be": "〜かもしれない",
"once and for all": "きっぱりと、これを最後に",
"lose my patience": "我慢の限界だ",
"enter": "入る",
"dominions": "領地",
"found myself": "気づくと〜だった",
"wreck": "台無しにする",
"dealt with": "対処される",
"rose": "立ち上がった（riseの過去形）",
"looked Edmund full in the face": "エドマンドの顔を真正面から見つめた",
"her eyes flaming": "目を燃え立たせて",
"wand": "杖",
"unable": "できない",
"gave himself up for lost": "もう助からないと諦めた",
"appeared to": "〜するように見えた",
"change her mind": "気が変わる",
"voice": "声",
"sledge": "そり",
"mantle": "外套（マント）",
"arrangement": "取り決め",
"dared not disobey": "あえて逆らわなかった",
"stepped onto": "〜に乗った",
"at her feet": "彼女の足元に",
"fold": "折り重なった部分",
"tucked it well in": "しっかりと巻きつけた",
"chattering": "（歯が）ガチガチ鳴ること",
"wrappings": "身にまとった衣類",
"copper": "銅",
"holding out her arm": "腕を差し出して",
"mid-air": "空中で",
"hissing": "シューという音",
"jewelled": "宝石で飾られた",
"steamed": "湯気を立てた",
"sip": "一口飲む",
"foamy": "泡立った",
"creamy": "クリームのような",
"right down to": "〜の先まですっかり",
"toes": "つま先",
"dull": "つまらない",
"instantly": "すぐに",
"turned out to": "〜だとわかった",
"several pounds of": "数ポンドの",
"to the very center": "芯まで",
"comfortable": "心地よい",
"rude": "失礼な",
"with one's mouth full": "口をいっぱいにしたまま",
"shovel down": "がつがつ食べる",
"the more he ate the more he wanted": "食べれば食べるほど欲しくなった",
"especially": "特に",
"coming back to": "（話題に）何度も戻ること",
"neither more nor less": "多くも少なくもなく",
"Turkish Delight": "ターキッシュ・ディライト（お菓子）",
"seem to mind": "気にしていないようだ",
"quite well": "よくわかって",
"enchanted": "魔法のかかった",
"offer": "差し出す",
"bring": "連れてくる",
"magic": "魔法",
"another matter": "別の話",
"drive away": "車で連れ去る",
"fear": "恐れ",
"lovely": "すてきな",
"of my own": "自分自身の",
"bring up": "育てる",
"cleverest": "一番賢い",
"handsomest": "一番ハンサムな",
"sticky": "べたべたした",
"whatever the Queen might say": "女王が何と言おうと",
"charming": "魅力的な",
"relations": "親族",
"later on": "後になって",
"understood": "了解されている",
"courtiers": "廷臣（宮廷に仕える人）",
"nobles": "貴族",
"duke": "公爵",
"duchesses": "公爵夫人",
"forget all about": "すっかり忘れる",
"bother": "面倒",
"fetch": "迎えに行く、取りに行く",
"no good": "無駄だ",
"pleaded": "懇願した",
"turned": "向きを変えた",
"Straight on": "まっすぐ進んで",
"beyond": "〜の向こうに",
"opposite direction": "反対方向",
"hills": "丘",
"rising above": "〜の上にそびえる",
"remember": "覚えておく",
"keep it a secret": "秘密にしておく",
"between us two": "私たち二人だけの",
"excuse": "口実",
"strange": "奇妙な",
"nasty": "嫌な",
"afraid": "恐れて",
"anything": "何でも",
"on the way home": "帰り道で",
"signaled": "合図した",
"drive on": "車を進ませる",
"swept away": "さっと走り去った",
"out of sight": "見えなくなって",
"waved": "手を振った",
"calling out": "大声で呼びかけて",
"staring after": "見えなくなるまで見つめること",
"looking round": "辺りを見回すこと",
"coming towards": "〜に向かって近づいてくること",
"right": "権利",
"be on the side": "味方する",
"good": "良い（人たち）",
}
